name: Build and Push

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  call-common-workflow:
    uses: tex-corver/.github/.github/workflows/docker-build-push.yaml@master
    with:
      project-name: tex-corver
      tag: v1
      port: 3000
      ingress: true
      ingress-domain: urieljsc.com
