name: Build and Push

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  REGISTRY: artifactory-jcr.artifactory-jcr.svc:8081
  IMAGE_NAME: docker/tex-corver

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run typecheck

      - name: Run linting
        run: npm run lint

      - name: Run build test
        run: npm run build

  build-and-push:
    needs: test
    runs-on: arc-runner-set
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: admin
          password: y9wb3N0Z3

      - name: Docker build
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v1 .

      - name: Docker push
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v1
        

  rollout-deployment:
    needs: build-and-push
    runs-on: arc-runner-set
    if: github.event_name == 'push'
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Rollout deployment
        run: |
          kubectl rollout restart -n tex-corver deployment tex-corver-landing-page